server:
  port: 8080   # recomiendo 8080 para el gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true      # útil si tus ids de servicio van en minúsculas
      routes:
        - id: customer-route
          uri: lb://customer               # nombre EXACTO del servicio (spring.application.name del micro)
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
        - id: bank_account-route
          uri: lb://bank_account
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
        - id: bank_card-route
          uri: lb://bank_card
          predicates:
            - Path=/api/cards/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
