server:
  port: 8081

spring:
  application:
    name: api-gateway

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-route
          uri: lb://persona-service
          predicates:
            - Path=/api/personas/**
          filters:
            - StripPrefix=1
