spring:
  application:
    name: bank_card
  data:
    mongodb:
      uri: "mongodb+srv://romcel87_db_user:OpUT3j2jbzWKCB69@cluster0.xgobikv.mongodb.net/bank_card?retryWrites=true&w=majority&tls=true"

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

    





